name: Build

on:
  push:
    branches: [ "main", "v2" ]
  pull_request:
    branches: [ "main", "v2" ]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: EyeLog.sln
      Platform: x86
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore packages
      run: nuget restore $env:Solution_Name 
      
    - name: Build solution
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=${{ matrix.configuration }} /p:Platform=$env:Platform  
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: EyeLog/bin/x86/Release/
